//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FO2Dat.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired
        {
            get
            {
                return ((bool)(this["UpgradeRequired"]));
            }
            set
            {
                this["UpgradeRequired"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int hdrNameWidth
        {
            get
            {
                return ((int)(this["hdrNameWidth"]));
            }
            set
            {
                this["hdrNameWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int hdrIsCompressedWidth
        {
            get
            {
                return ((int)(this["hdrIsCompressedWidth"]));
            }
            set
            {
                this["hdrIsCompressedWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int hdrSizeWidth
        {
            get
            {
                return ((int)(this["hdrSizeWidth"]));
            }
            set
            {
                this["hdrSizeWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int hdrPackedSizeWidth
        {
            get
            {
                return ((int)(this["hdrPackedSizeWidth"]));
            }
            set
            {
                this["hdrPackedSizeWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int hdrOffsetWidth
        {
            get
            {
                return ((int)(this["hdrOffsetWidth"]));
            }
            set
            {
                this["hdrOffsetWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int splContainerSplit
        {
            get
            {
                return ((int)(this["splContainerSplit"]));
            }
            set
            {
                this["splContainerSplit"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("294, 536")]
        public global::System.Drawing.Size trvTreeSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["trvTreeSize"]));
            }
            set
            {
                this["trvTreeSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("572, 536")]
        public global::System.Drawing.Size lstFilesSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["lstFilesSize"]));
            }
            set
            {
                this["lstFilesSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FormLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["FormLocation"]));
            }
            set
            {
                this["FormLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("922, 632")]
        public global::System.Drawing.Size FormSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["FormSize"]));
            }
            set
            {
                this["FormSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState FormState
        {
            get
            {
                return ((global::System.Windows.Forms.FormWindowState)(this["FormState"]));
            }
            set
            {
                this["FormState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Details")]
        public global::System.Windows.Forms.View lstFilesView
        {
            get
            {
                return ((global::System.Windows.Forms.View)(this["lstFilesView"]));
            }
            set
            {
                this["lstFilesView"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool lstFilesShowGroups
        {
            get
            {
                return ((bool)(this["lstFilesShowGroups"]));
            }
            set
            {
                this["lstFilesShowGroups"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int languageLCID
        {
            get
            {
                return ((int)(this["languageLCID"]));
            }
            set
            {
                this["languageLCID"] = value;
            }
        }
    }
}
